#!/usr/bin/env node
'use strict';

var spawnCommand = require('child_process').exec,
    restricted = [
      'refs/heads/master',
      'refs/heads/development',
      'refs/heads/develop'
    ];

spawnCommand('git symbolic-ref HEAD', function (error, stdout) {
  if (restricted.indexOf(stdout.trim()) !== -1) {
    console.log('You cannot commit to branch master or develop!');
    process.exit(1);
  }
});
