#!/bin/sh

SCRIPTNAME=$(basename $0)

RESTRICTED=(
    'refs/heads/master'
    'refs/heads/development'
    'refs/heads/develop'
    );

CURRENTBRANCH=$(git symbolic-ref HEAD)

for i in "${RESTRICTED[@]}"
do
    if [[ "${CURRENTBRANCH}" == "${i}"* ]]
    then
        echo ${SCRIPTNAME}: ${i} is restricted !
        exit 1
    fi
done

echo ${SCRIPTNAME}: ${CURRENTBRANCH} is allowed
